// ReSharper disable InconsistentNaming
#pragma warning disable CA1707 // Identifiers should not contain underscores
namespace Plugin.Bluetooth.PlatformSpecific;

public enum GattCallbackStatus
{
    GATT_SUCCESS = 0x00,

    GATT_INVALID_HANDLE = 0x01,

    GATT_READ_NOT_PERMIT = 0x02,

    GATT_WRITE_NOT_PERMIT = 0x03,

    GATT_INVALID_PDU = 0x04,

    GATT_INSUF_AUTHENTICATION = 0x05,

    GATT_REQ_NOT_SUPPORTED = 0x06,

    GATT_INVALID_OFFSET = 0x07,

    GATT_INSUF_AUTHORIZATION = 0x08,

    GATT_PREPARE_Q_FULL = 0x09,

    GATT_NOT_FOUND = 0x0a,

    GATT_NOT_LONG = 0x0b,

    GATT_INSUF_KEY_SIZE = 0x0c,

    GATT_INVALID_ATTR_LEN = 0x0d,

    GATT_ERR_UNLIKELY = 0x0e,

    GATT_INSUF_ENCRYPTION = 0x0f,

    GATT_UNSUPPORT_GRP_TYPE = 0x10,

    GATT_INSUF_RESOURCE = 0x11,

    GATT_CONN_LMP_TIMEOUT = 0x22,

    GATT_CONTROLLER_BUSY = 0x3A,

    GATT_UNACCEPT_CONN_INTERVAL = 0x3B,

    GATT_ILLEGAL_PARAMETER = 0x87,

    GATT_NO_RESOURCES = 0x80,

    GATT_INTERNAL_ERROR = 0x81,

    GATT_WRONG_STATE = 0x82,

    GATT_DB_FULL = 0x83,

    GATT_BUSY = 0x84,

    GATT_ERROR = 0x85,

    GATT_CMD_STARTED = 0x86,

    GATT_PENDING = 0x88,

    GATT_AUTH_FAIL = 0x89,

    GATT_MORE = 0x8a,

    GATT_INVALID_CFG = 0x8b,

    GATT_SERVICE_STARTED = 0x8c,

    GATT_ENCRYPTED_NO_MITM = 0x8d,

    GATT_NOT_ENCRYPTED = 0x8e,

    GATT_CONGESTED = 0x8f,

    GATT_CCCD_CFG_ERROR = 0xFD,

    GATT_PROCEDURE_IN_PROGRESS = 0xFE,

    GATT_VALUE_OUT_OF_RANGE = 0xFF,

    TOO_MANY_OPEN_CONNECTIONS = 0x0101,

    // DFU_SECURE
    DFU_SECURE_OP_CODE_NOT_SUPPORTED = 514,

    DFU_SECURE_INVALID_PARAM = 515,

    DFU_SECURE_INSUFFICIENT_RESOURCES = 516,

    DFU_SECURE_INVALID_OBJECT = 517,

    DFU_SECURE_UNSUPPORTED_TYPE = 519,

    DFU_SECURE_OPERATION_NOT_PERMITTED = 520,

    DFU_SECURE_OPERATION_FAILED = 522,

    DFU_SECURE_EXTENDED_ERROR = 523,

    // DFU_SECURE_EXTENDED
    DFU_SECURE_EXTENDED_WRONG_COMMAND_FORMAT = 1026,

    DFU_SECURE_EXTENDED_UNKNOWN_COMMAND = 1027,

    DFU_SECURE_EXTENDED_INIT_COMMAND_INVALID = 1028,

    DFU_SECURE_EXTENDED_FW_VERSION_FAILURE = 1029,

    DFU_SECURE_EXTENDED_HW_VERSION_FAILURE = 1030,

    DFU_SECURE_EXTENDED_SD_VERSION_FAILURE = 1031,

    DFU_SECURE_EXTENDED_SIGNATURE_MISMATCH = 1032,

    DFU_SECURE_EXTENDED_WRONG_HASH_TYPE = 1033,

    DFU_SECURE_EXTENDED_HASH_FAILED = 1034,

    DFU_SECURE_EXTENDED_WRONG_SIGNATURE_TYPE = 1035,

    DFU_SECURE_EXTENDED_VERIFICATION_FAILED = 1036,

    DFU_SECURE_EXTENDED_INSUFFICIENT_SPACE = 1037,

    // DFU_SECURE_BUTTONLESS
    DFU_SECURE_BUTTONLESS_OP_CODE_NOT_SUPPORTED = 2050,

    DFU_SECURE_BUTTONLESS_OPERATION_FAILED = 2052,

    // DFU_COMMON_DFU_ERRORS
    DFU_DEVICE_DISCONNECTED = 4096,

    DFU_FILE_NOT_FOUND = 4097,

    DFU_FILE_ERROR = 4098,

    DFU_NOT_A_VALID_HEX_FILE = 4099,

    DFU_IO_EXCEPTION = 4100,

    DFU_SERVICE_DISCOVERY_NOT_STARTED = 4101,

    DFU_CHARACTERISTICS_NOT_FOUND = 4102,

    DFU_INVALID_RESPONSE = 4104,

    DFU_FILE_TYPE_NOT_SUPPORTED = 4105,

    BLUETOOTH_ADAPTER_DISABLED = 4106,

    DFU_INIT_PACKET_REQUIRED = 4107,

    DFU_INIT_PACKET_REQUIRED2 = 4108,

    DFU_CRC_ERROR = 4109,

    DFU_DEVICE_NOT_BONDED = 4110
}

#pragma warning restore CA1707 // Identifiers should not contain underscores
